on: [workflow_dispatch]

name: containerd cache

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-tag-e2e-tests
      - nscloud-cache-size-2gb
      - nscloud-exp-container-image-cache
      - nscloud-no-remote-builders
      - nscloud-git-mirror-5gb
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          ls /
          cd /cache && df -h .
          ls -lta /cache

      - uses: actions/checkout@v3

      - run: |
          time docker pull ubuntu
  
