on: [push, workflow_dispatch]

name: features

jobs:
  ci:
    runs-on: nscloud, nscloud-exp-locale-utf8
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
          locale

      - uses: actions/checkout@v3
