on: [workflow_dispatch]

name: simple-with-matrix

jobs:
  ci:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [nscloud-ubuntu-22.04-amd64-2x4, nscloud-ubuntu-22.04-amd64-2x4, nscloud-ubuntu-22.04-amd64-2x4, nscloud-ubuntu-22.04-amd64-2x4]
        dummy_env: [dummy1, dummy2, dummy3, dummy4, dummy5]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Env checks
        env:
          DUMMY_ENV: ${{ matrix.dummy_env }}
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json

      # - name: Breakpoint if tests failed
      #   uses: namespacelabs/breakpoint-action@v0
      #   with:
      #     duration: 30m
      #     authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,pavolmarko

      - uses: actions/checkout@v3

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
          
  job1:
    runs-on: nscloud-ubuntu-22.04-amd64-4x16
    steps:
    - uses: actions/checkout@v3

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
    
  job2:
    needs: job1
    runs-on: nscloud-ubuntu-22.04-amd64-4x16
    steps:
    - uses: actions/checkout@v3

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
