on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on: 
      - nscloud-ubuntu-22.04-staging-amd64-4x16
    steps:
      - uses: actions/checkout@v3

      - run: |
          cat $GITHUB_ENV
          echo ${{ env.NSC_CONTAINER_REGISTRY }}
      # - name: Env checks
      #   run: |
      #     nsc version
      #     ps aux
      #     ulimit -a
      #     aws --version
      #     docker buildx ls 
      #     env
      #     cat ~/.docker/config.json
      #     uname -a
      #     ls -lta /
      #     ls -lta /cache

      - run: ls -lta /usr/lib/jvm
      - run: env
      - run: ant -version
      # Test dotnet installer (proinc)
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 
          cache: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: pip install pre-commit

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
      
      - run: |
          time docker pull ubuntu
  ci-gh-runner:
    runs-on: ubuntu-20.04
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a

      - run: ls /usr/share/dotnet/sdk
      - run: dpkg -S dotnet

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 
          cache: false
