on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on: 
      - namespace-profile-test
    steps:
      # - name: Env checks
      #   run: |
      #     ulimit -a
      #     aws --version
      #     docker buildx ls 
      #     env
      #     cat ~/.docker/config.json
      #     uname -a
      #     ls -lta /
      #     ls -lta /cache

      - uses: namespacelabs/nscloud-checkout-action@v1
        with:
          fetch-depth: 10

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'

      
      - run: |
          time docker pull ubuntu

      - run:
          psql --version
  ci-gh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
