on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on: 
      - namespace-profile-gmichelo1
    steps:
      - uses: actions/checkout@v3
      # - run: |
      #     docker run ubuntu /bin/sh -c 'sleep 1000'
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
      
      - name: run time
        run: |
          time

      - run: |
          cat $GITHUB_ENV
          echo ${{ env.NSC_CONTAINER_REGISTRY }}
      - name: Env checks
        run: |
          nsc version
          ps aux
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
          ls -lta /
          ls -lta /cache
          
      - uses: namespacelabs/nscloud-checkout-action@v1
        with:
          fetch-depth: 10

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'

      
      - run: |
          time docker pull ubuntu
  ci-gh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
