on: [workflow_dispatch]

name: simple-arm64

jobs:
  ci:
    strategy:
      matrix:
        dummy_env: [dummy1, dummy2, dummy3, dummy4, dummy5]
    runs-on: self-hosted
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json

      - uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nscr.io/01gr1g2rpb7ahzddy3f227exq9/testdocker:latest
